# spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER

spring:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mariadb://localhost:3306/hbj
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mariadb

  jpa:

    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
